print("  Welcome to the Band Name Generator")
print("---------------------------------------")
city = input("What city did you grow up in?\n")
pet = input("What is your pet's name?\n")
print("Your band name could be " + city + " " + pet)
